[build]
  # Directory to publish (your app root since you're serving static files from root)
  publish = "."

# Redirect rules (these will override your _redirects file)
[[redirects]]
  # Force HTTPS and www for apex domain HTTP
  from = "http://stellah.ai/*"
  to = "https://www.stellah.ai/:splat"
  status = 301
  force = true

[[redirects]]
  # Force HTTPS for www HTTP
  from = "http://www.stellah.ai/*"
  to = "https://www.stellah.ai/:splat"
  status = 301
  force = true

[[redirects]]
  # Force apex domain to www (HTTPS)
  from = "https://stellah.ai/*"
  to = "https://www.stellah.ai/:splat"
  status = 301
  force = true

[[redirects]]
  # SPA fallback - redirect all other requests to index.html for client-side routing
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"